services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ticket_link
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: